name: Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16      
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: TestAdd
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v github.com/Dynatrace-Reinhard-Pilz/vs-code-sample/add